  
 MODULE mod_chem_spack_rates
  
   IMPLICIT NONE
   PRIVATE
   PUBLIC :: rates ! subroutine
 CONTAINS
  
   SUBROUTINE rates(rk,y,w,ngas,ijkbeg,ijkend,maxblock_size,nr)
 
!------------------------------------------------------------------------
!
!     -- DESCRIPTION
!
!     This routine computes the reaction rates.
!     This routine is automatically generated by SPACK.
!     Mechanism: ../Mechanism/LPCE2  
!     Species: ../Mechanism/ciLPCE2
!
!------------------------------------------------------------------------
!
!     -- INPUT VARIABLES
!
!     RK: kinetic rates.
!     Y: chemical concentrations.
!
!     -- INPUT/OUTPUT VARIABLES
!
!     -- OUTPUT VARIABLES
!
!     W: reaction rates.
!
!------------------------------------------------------------------------
!
!     -- REMARKS
!
!------------------------------------------------------------------------
!
!     -- MODIFICATIONS
!
!------------------------------------------------------------------------
!
!     -- AUTHOR(S)
!
!     SPACK.
!
!------------------------------------------------------------------------
 
      IMPLICIT NONE
 
 
 
      INTEGER  	, INTENT(IN)  :: ngas	               
      INTEGER  	, INTENT(IN)  :: ijkbeg 	       
      INTEGER  	, INTENT(IN)  :: ijkend 	       
      INTEGER  	, INTENT(IN)  :: maxblock_size	       
      INTEGER  	, INTENT(IN)  :: nr		       
      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)  
      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS) 
      DOUBLE PRECISION , INTENT(OUT) :: w(maxblock_size,nr)   
      INTEGER  	, INTENT(IN)  :: ijk		       
 
      DO ijk=ijkbeg,ijkend
      w(ijk,  1) =  rk(ijk,  1) * Y(ijk,  2) * Y(ijk,  1)
      w(ijk,  2) =  rk(ijk,  2) * Y(ijk,  3) * Y(ijk,  1)
       END DO
 
   END SUBROUTINE rates
 
  END MODULE mod_chem_spack_rates
 
