 MODULE mod_chem_spack_kinetic
  
   IMPLICIT NONE
   PRIVATE
   PUBLIC :: kinetic ! subroutine
 CONTAINS
   SUBROUTINE kinetic(jppj,Jphoto,rk,temp,xlw,Press,cosz,att,ijkbeg,ijkend,maxblock_size,nr)
 
!------------------------------------------------------------------------
!
!     -- DESCRIPTION
!
!     This routine computes the kinetic rates for the gas-phase.
!     This routine is automatically generated by SPACK.
!     Mechanism: ../Mechanism/HETEST 
!     Species: ../Mechanism/ciHETR 
!
!------------------------------------------------------------------------
!
!     -- INPUT VARIABLES
!
!     TEMP: temperature ([K]).
!     XLW: water massic fraction.
!     PRESS: pressure ([Pa]).
!     ATT: attenuation variable.
!
!     -- INPUT/OUTPUT VARIABLES
!
!     -- OUTPUT VARIABLES
!
!     RK: kinetic rates.
!
!------------------------------------------------------------------------
!
!     -- REMARKS
!
!------------------------------------------------------------------------
!
!     -- MODIFICATIONS
!
!------------------------------------------------------------------------
!
!     -- AUTHOR(S)
!
!     SPACK.
!
!------------------------------------------------------------------------
 
      IMPLICIT NONE
 
 
 
      INTEGER,INTENT(IN) :: jppj,ijkbeg,ijkend,maxblock_size,nr
      DOUBLE PRECISION,INTENT(IN) ::  xlw(maxblock_size),att(maxblock_size),cosz(maxblock_size)
      DOUBLE PRECISION,INTENT(IN) ::  temp(maxblock_size),Press(maxblock_size)
      DOUBLE PRECISION,INTENT(OUT) ::  rk(maxblock_size,nr)
      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur
      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi
      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)
      INTEGER :: ijk
 
!     Compute third body.
!     Conversion = Avogadro*1d-6/Perfect gas constant.
!     PRESS in Pascal, SUMM in molecules/cm3, TEMP in Kelvin
 
      DO ijk=ijkbeg,ijkend
        SumM(ijk) = Press(ijk) * 7.243D16 / temp(ijk)
      END DO
 
!     Number of water molecules computed from the massic fraction
!     (absolute humidity)
 
      DO ijk=ijkbeg,ijkend
         YlH2O(ijk) = 29.d0*SumM(ijk)*xlw(ijk)/(18.d0+11.d0*xlw(ijk))
      END DO
 
!     For the zenithal angle at tropics
 
 
 
       DO ijk=ijkbeg,ijkend
       rk(ijk,  1) = Jphoto(ijk,  1)
       rk(ijk,  2) = Jphoto(ijk,  2)
       rk(ijk,  3) = Jphoto(ijk,  3)
       rk(ijk,  4) = Jphoto(ijk,  4)
       rk(ijk,  5) = Jphoto(ijk,  5)
       rk(ijk,  6) = Jphoto(ijk,  6)
       rk(ijk,  7) = Jphoto(ijk,  7)
       rk(ijk,  8) = Jphoto(ijk,  8)
       rk(ijk,  9) = Jphoto(ijk,  9)
       rk(ijk, 10) = Jphoto(ijk, 10)
       rk(ijk, 11) = Jphoto(ijk, 11)
       rk(ijk, 12) = Jphoto(ijk, 12)
       rk(ijk, 13) = Jphoto(ijk, 13)
       rk(ijk, 14) = Jphoto(ijk, 14)
       rk(ijk, 15) = Jphoto(ijk, 15)
       rk(ijk, 16) = Jphoto(ijk, 16)
       rk(ijk, 17) = Jphoto(ijk, 17)
       rk(ijk, 18) = Jphoto(ijk, 18)
       rk(ijk, 19) = Jphoto(ijk, 19)
      rk(ijk, 20) = SumM(ijk) * 6.0d-34 * (temp(ijk)/3.d2) ** (-2.3d0)
      rk(ijk, 20) = rk(ijk, 20) * SumM(ijk) * 0.2d0
      rk(ijk, 21) =  DEXP(-0.2555157957424871D+02   &
         - (  0.2060000000000000D+04 )/temp(ijk))
      rk(ijk, 22) =  DEXP(-0.2474064935803238D+02   &
         - ( -0.1100000000000000D+03 )/temp(ijk))
      rk(ijk, 22) = rk(ijk, 22) * SumM(ijk) * 0.8d0
      rk(ijk, 23) =  DEXP(-0.2416528521312882D+02   &
         - ( -0.7000000000000000D+02 )/temp(ijk))
      rk(ijk, 23) = rk(ijk, 23) * SumM(ijk) * 0.2d0
      rk(ijk, 24) =  0.2200000000000000D-09
      rk(ijk, 24) = rk(ijk, 24) * YlH2O(ijk)
      rk(ijk, 25) =  0.1100000000000000D-09
      rk(ijk, 26) =  DEXP(-0.2716101748668281D+02   &
         - (  0.9400000000000000D+03 )/temp(ijk))
      rk(ijk, 27) =  DEXP(-0.3214088112211231D+02   &
         - (  0.5000000000000000D+03 )/temp(ijk))
      rk(ijk, 28) =  DEXP(-0.2375982010502066D+02   &
         - ( -0.2500000000000000D+03 )/temp(ijk))
      rk(ijk, 29) =  DEXP(-0.2656631037893612D+02   &
         - (  0.1600000000000000D+03 )/temp(ijk))
      rk(ijk, 30) = 2.2d-13 * dexp(620.0d0 / temp(ijk))   &
                    + 1.9d-33* SumM(ijk) * dexp(980.0d0 / temp(ijk))
      rk(ijk, 31) = 3.08d-34 * dexp(2820.0d0 / temp(ijk)) +    &
                    2.66d-54 * SumM(ijk) * dexp(3180.0d0 / temp(ijk))
      rk(ijk, 31) = rk(ijk, 31) * YlH2O(ijk)
      Effko(ijk) =  0.9000000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.1500000000000000D+01))
      Rapk(ijk) =  0.3000000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.0000000000000000D+00))
      rk(ijk, 32) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 33) =  DEXP(-0.2575921893902696D+02   &
         - ( -0.1200000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.9000000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.2000000000000000D+01))
      Rapk(ijk) =  0.2200000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.0000000000000000D+00))
      rk(ijk, 34) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      Effko(ijk) =  0.7000000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.2600000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.5000000000000000D+00))
      rk(ijk, 35) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      Effko(ijk) =  0.2600000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.2400000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1300000000000000D+01))
      rk(ijk, 36) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 37) =  0.2200000000000000D-10
      rk(ijk, 38) =  DEXP(-0.2632268829627837D+02   &
         - ( -0.2500000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.1800000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.4700000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1400000000000000D+01))
      rk(ijk, 39) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 40) =  DEXP( 0.6142746008608852D+02   &
         - (  0.1090000000000000D+05 )/temp(ijk))
      Effko(ijk) =  0.1800000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.4700000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1400000000000000D+01))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 40) = facteur(ijk) * rk(ijk, 40)
      rk(ijk, 41) =  0.3500000000000000D-11
      rk(ijk, 42) =  DEXP(-0.2474064935803238D+02   &
         - (  0.3900000000000000D+03 )/temp(ijk))
      Effko(ijk) = 7.2d-15 * dexp(785.0d0 / temp(ijk))
      Rapk(ijk) = 4.1d-16 * dexp(1440.0d0 / temp(ijk))
      facteur(ijk) =1.9d-33 * dexp(725.0d0 / temp(ijk)) * SumM(ijk)
      rk(ijk, 43) = Effko(ijk) + facteur(ijk)/(1.0d0 + facteur(ijk) / Rapk(ijk))
      rk(ijk, 44) =  DEXP(-0.2736865685146106D+02   &
         - ( -0.3800000000000000D+03 )/temp(ijk))
      rk(ijk, 45) =  DEXP(-0.2693787393536860D+02   &
         - (  0.1400000000000000D+04 )/temp(ijk))
      rk(ijk, 46) =  DEXP(-0.2975128465212864D+02   &
         - (  0.2450000000000000D+04 )/temp(ijk))
      rk(ijk, 47) =  DEXP(-0.8860689615829534D+02   &
         - ( -0.5300000000000000D+03 )/temp(ijk))
      rk(ijk, 47) = rk(ijk, 47) * SumM(ijk) * 0.2d0
      rk(ijk, 48) =  DEXP(-0.2492297091482634D+02   &
         - ( -0.1700000000000000D+03 )/temp(ijk))
      rk(ijk, 49) =  DEXP(-0.3073211390514037D+02   &
         - (  0.1260000000000000D+04 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3900000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.7000000000000000D+00))
      rk(ijk, 50) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 51) =  DEXP( 0.6117554523749536D+02   &
         - (  0.1100000000000000D+05 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3900000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.7000000000000000D+00))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 51) = facteur(ijk) * rk(ijk, 51)
      rk(ijk, 52) =  DEXP(-0.2779354004542632D+02   &
         - (  0.2450000000000000D+04 )/temp(ijk))
      rk(ijk, 53) =  DEXP(-0.2660140169874739D+02   &
         - (  0.1800000000000000D+04 )/temp(ijk))
      rk(ijk, 54) = 1.5d-13 * (1.0d0 + 2.439d-20 * SumM(ijk))
      rk(ijk, 55) =  DEXP(-0.3943966082504782D+02   &
        + ( 0.2000000000000000D+01 * LOG(temp(ijk)))   &
        -  0.1361000000000000D+04/temp(ijk))
      rk(ijk, 56) =  0.9999999999999999D-11
      rk(ijk, 57) =  DEXP(-0.2655601869289957D+02   &
         - ( -0.1900000000000000D+03 )/temp(ijk))
      rk(ijk, 58) =  DEXP(-0.2870983077730048D+02   &
         - (  0.1900000000000000D+04 )/temp(ijk))
      rk(ijk, 59) =  DEXP(-0.2619593659063922D+02   &
         - ( -0.1800000000000000D+03 )/temp(ijk))
      rk(ijk, 60) =  DEXP(-0.2859860514219026D+02   &
         - ( -0.8000000000000000D+03 )/temp(ijk))
      rk(ijk, 61) =  DEXP(-0.3002791688839384D+02   &
         - ( -0.4160000000000000D+03 )/temp(ijk))
      rk(ijk, 62) =  0.1200000000000000D-11
      rk(ijk, 63) =  DEXP(-0.2323657196125611D+02   &
         - (  0.3000000000000000D+02 )/temp(ijk))
      rk(ijk, 64) =  DEXP(-0.2643709864745611D+02   &
         - (  0.1150000000000000D+03 )/temp(ijk))
      rk(ijk, 65) =  DEXP(-0.2426372528594207D+02   &
         - (  0.2600000000000000D+03 )/temp(ijk))
      rk(ijk, 66) =  DEXP(-0.2577472312556292D+02   &
         - ( -0.2900000000000000D+03 )/temp(ijk))
      rk(ijk, 67) =  DEXP(-0.2426372528594207D+02   &
         - (  0.2600000000000000D+03 )/temp(ijk))
      rk(ijk, 68) =  DEXP(-0.2523312584313018D+02   &
         - (  0.1400000000000000D+04 )/temp(ijk))
      rk(ijk, 69) =  DEXP(-0.2402010320328433D+02   &
         - (  0.2300000000000000D+04 )/temp(ijk))
      rk(ijk, 69) = rk(ijk, 69) * SumM(ijk) * 5.8d-7
      rk(ijk, 70) =  DEXP(-0.2474064935803238D+02   &
         - ( -0.1700000000000000D+03 )/temp(ijk))
      rk(ijk, 71) =  DEXP(-0.2391744904922424D+02   &
         - (  0.4500000000000000D+03 )/temp(ijk))
      rk(ijk, 72) =  DEXP(-0.2531848569208134D+02   &
         - ( -0.1200000000000000D+03 )/temp(ijk))
      rk(ijk, 73) =  DEXP(-0.2775885448743843D+02   &
         - ( -0.1200000000000000D+03 )/temp(ijk))
      rk(ijk, 74) =  DEXP(-0.2667550967090111D+02   &
         - (  0.3500000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.1800000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3400000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1900000000000000D+01))
      rk(ijk, 75) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 76) =  DEXP(-0.2836499029100875D+02   &
         - ( -0.7000000000000000D+03 )/temp(ijk))
      rk(ijk, 77) =  DEXP(-0.2653240882726044D+02   &
         - (  0.5000000000000000D+03 )/temp(ijk))
      rk(ijk, 78) =  0.1700000000000000D-12
      rk(ijk, 79) =  DEXP(-0.2671473038405439D+02   &
         - (  0.1300000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3100000000000000D+01))
      Rapk(ijk) =  0.3500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1000000000000000D+01))
      rk(ijk, 80) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 81) =  DEXP( 0.6190713320136274D+02   &
         - (  0.8744000000000000D+04 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3100000000000000D+01))
      Rapk(ijk) =  0.3500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1000000000000000D+01))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 81) = facteur(ijk) * rk(ijk, 81)
      rk(ijk, 82) =  DEXP(-0.2763102111592855D+02   &
         - (  0.1590000000000000D+04 )/temp(ijk))
      rk(ijk, 83) =  DEXP(-0.2422982373426639D+02   &
         - (  0.2450000000000000D+04 )/temp(ijk))
      rk(ijk, 84) =  DEXP(-0.2656631037893612D+02   &
         - (  0.8000000000000000D+03 )/temp(ijk))
      rk(ijk, 85) =  DEXP(-0.2479780777187233D+02   &
         - (  0.8000000000000000D+03 )/temp(ijk))
      rk(ijk, 86) =  DEXP(-0.2479780777187233D+02   &
         - (  0.8000000000000000D+03 )/temp(ijk))
      rk(ijk, 87) =  DEXP(-0.2468658213676211D+02   &
         - ( -0.2300000000000000D+03 )/temp(ijk))
      rk(ijk, 88) =  DEXP(-0.2545626939444439D+02   &
         - ( -0.2600000000000000D+03 )/temp(ijk))
      rk(ijk, 89) =  DEXP(-0.2722555600782038D+02   &
         - ( -0.2300000000000000D+03 )/temp(ijk))
      rk(ijk, 90) =  DEXP(-0.2492297091482634D+02   &
         - (  0.6000000000000000D+03 )/temp(ijk))
      rk(ijk, 91) =  0.1500000000000000D-09
      rk(ijk, 92) =  0.9999999999999999D-11
      rk(ijk, 93) =  0.1100000000000000D-10
      Effko(ijk) =  0.5200000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.6900000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.2900000000000000D+01))
      rk(ijk, 94) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 95) =  DEXP(-0.2640724568430643D+02   &
         - ( -0.5400000000000000D+03 )/temp(ijk))
      rk(ijk, 96) =  DEXP(-0.2284352937314650D+02   &
         - (  0.4300000000000000D+03 )/temp(ijk))
       END DO
 
   END SUBROUTINE kinetic
 
  END MODULE mod_chem_spack_kinetic
 
