                                                                                
 MODULE mod_chem_spack_fexprod                                                  
                                                                                
   IMPLICIT NONE                                                                
   PRIVATE                                                                      
   PUBLIC :: fexprod ! subroutine                                               
 CONTAINS                                                                       
                                                                                
   SUBROUTINE fexprod(w,prod,ngas,ijkbegin,ijkend,maxblock_size,nr)             
                                                                                
!------------------------------------------------------------------------       
!                                                                               
!     -- DESCRIPTION                                                            
!                                                                               
!     This routine computes the production  term P in a P-Lc formulation.       
!     This routine is automatically generated by SPACK.                         
!     Mechanism: ../Mechanism/HETEST                                            
!     Species: ../Mechanism/ciHETR                                              
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- INPUT VARIABLES                                                        
!                                                                               
!     W: reaction rates.                                                        
!                                                                               
!     -- INPUT/OUTPUT VARIABLES                                                 
!                                                                               
!     -- OUTPUT VARIABLES                                                       
!                                                                               
!     PROD: array of chemical production terms.                                 
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- REMARKS                                                                
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- MODIFICATIONS                                                          
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- AUTHOR(S)                                                              
!                                                                               
!     SPACK.                                                                    
!                                                                               
!------------------------------------------------------------------------       
                                                                                
                                                                                
                                                                                
       IMPLICIT NONE                                                            
                                                                                
      INTEGER  	, INTENT(IN)  :: ngas                                           
      INTEGER  	, INTENT(IN)  :: ijkbegin		                                     
      INTEGER  	, INTENT(IN)  :: ijkend 		                                      
      INTEGER  	, INTENT(IN)  :: maxblock_size		                                
      INTEGER  	, INTENT(IN)  :: nr		      	                                    
      DOUBLE PRECISION , INTENT(IN)  :: w(maxblock_size,nr)	                    
      DOUBLE PRECISION , INTENT(OUT) :: prod(maxblock_size,NGAS)                
      INTEGER :: ijk						                                                      
                                                                                
                                                                                
!     Chemical production terms.                                                
                                                                                
      DO ijk=ijkbegin,ijkend                                                    
      prod(ijk,  1) = + w(ijk, 20)
      prod(ijk,  2) = + w(ijk, 10)
      prod(ijk,  3) = + w(ijk, 30) &
          + w(ijk, 31)
      prod(ijk,  4) = + w(ijk,  1) &
          + w(ijk,  4) &
          + w(ijk,  7) &
          + w(ijk, 33) &
          + w(ijk, 49)
      prod(ijk,  5) = + w(ijk,  5) &
          + w(ijk,  6) &
          + w(ijk,  8) &
          + w(ijk, 14) &
          + w(ijk, 32) &
          + w(ijk, 37) &
          + w(ijk, 38) &
          + w(ijk, 40) &
          +  0.7000000000000000D+00 * w(ijk, 41) &
          + w(ijk, 42) &
          + w(ijk, 44) &
          + w(ijk, 45) &
          +  0.2000000000000000D+01 * w(ijk, 47) &
          +  0.2000000000000000D+01 * w(ijk, 48) &
          + w(ijk, 51) &
          +  0.2000000000000000D+01 * w(ijk, 52) &
          + w(ijk, 59) &
          + w(ijk, 62) &
          + w(ijk, 64) &
          + w(ijk, 66) &
          + w(ijk, 88)
      prod(ijk,  6) = + w(ijk, 13) &
          + w(ijk, 18) &
          + w(ijk, 34) &
          + w(ijk, 43) &
          + w(ijk, 46) &
          + w(ijk, 51) &
          + w(ijk, 84)
      prod(ijk,  7) = + w(ijk, 50)
      prod(ijk,  8) = + w(ijk, 35)
      prod(ijk,  9) = + w(ijk, 36) &
          +  0.3000000000000000D+00 * w(ijk, 41) &
          + w(ijk, 58)
      prod(ijk, 10) = + w(ijk, 39)
      prod(ijk, 11) = + w(ijk, 10) &
          + w(ijk, 11) &
          + w(ijk, 56) &
          + w(ijk, 58) &
          + w(ijk, 63) &
          + w(ijk, 85)
      prod(ijk, 12) = + w(ijk,  1) &
          + w(ijk,  3) &
          + w(ijk,  8) &
          + w(ijk, 17) &
          + w(ijk, 22) &
          + w(ijk, 23)
      prod(ijk, 13) = + w(ijk,  2)
      prod(ijk, 14) = + w(ijk,  4) &
          + w(ijk,  5) &
          +  0.2000000000000000D+01 * w(ijk,  9) &
          + w(ijk, 12) &
          + w(ijk, 19) &
          +  0.2000000000000000D+01 * w(ijk, 24) &
          + w(ijk, 25) &
          + w(ijk, 27) &
          + w(ijk, 38) &
          +  0.7000000000000000D+00 * w(ijk, 41) &
          + w(ijk, 71) &
          + w(ijk, 78) &
          + w(ijk, 79) &
          + w(ijk, 91) &
          + w(ijk, 96)
      prod(ijk, 15) = + w(ijk,  6) &
          +  0.2000000000000000D+01 * w(ijk, 11) &
          + w(ijk, 12) &
          + w(ijk, 25) &
          + w(ijk, 26) &
          + w(ijk, 29) &
          + w(ijk, 37) &
          + w(ijk, 40) &
          + w(ijk, 53) &
          + w(ijk, 54) &
          + w(ijk, 56) &
          + w(ijk, 58) &
          + w(ijk, 59) &
          +  0.6600000000000000D+00 * w(ijk, 61) &
          + w(ijk, 62) &
          + w(ijk, 63) &
          + w(ijk, 72) &
          + w(ijk, 85) &
          + w(ijk, 92)
      prod(ijk, 17) = + w(ijk, 12) &
          +  0.3500000000000000D+00 * w(ijk, 57) &
          + w(ijk, 59) &
          +  0.1330000000000000D+01 * w(ijk, 61) &
          + w(ijk, 62) &
          + w(ijk, 64)
      prod(ijk, 18) = + w(ijk, 60)
      prod(ijk, 19) = + w(ijk, 55) &
          +  0.6500000000000000D+00 * w(ijk, 57) &
          + w(ijk, 68)
      prod(ijk, 20) = + w(ijk, 13) &
          +  0.2000000000000000D+01 * w(ijk, 15) &
          +  0.2000000000000000D+01 * w(ijk, 16) &
          + w(ijk, 64) &
          + w(ijk, 66) &
          + w(ijk, 67) &
          + w(ijk, 72) &
          + w(ijk, 74)
      prod(ijk, 21) = + w(ijk, 63) &
          + w(ijk, 68) &
          + w(ijk, 69) &
          + w(ijk, 70) &
          + w(ijk, 73)
      prod(ijk, 22) = + w(ijk, 14) &
          + w(ijk, 65) &
          + w(ijk, 71) &
          + w(ijk, 77) &
          + w(ijk, 78) &
          +  0.2000000000000000D+01 * w(ijk, 81) &
          + w(ijk, 84)
      prod(ijk, 23) = + w(ijk, 75)
      prod(ijk, 24) = + w(ijk, 76)
      prod(ijk, 25) = + w(ijk, 80)
      prod(ijk, 26) = + w(ijk, 79) &
          + w(ijk, 82) &
          + w(ijk, 83)
      prod(ijk, 27) = + w(ijk, 86) &
          + w(ijk, 96)
      prod(ijk, 28) = + w(ijk, 17) &
          + w(ijk, 18) &
          + w(ijk, 19) &
          + w(ijk, 87) &
          + w(ijk, 88) &
          +  0.2000000000000000D+01 * w(ijk, 89) &
          + w(ijk, 91) &
          + w(ijk, 92) &
          + w(ijk, 93)
      prod(ijk, 29) = + w(ijk, 85) &
          + w(ijk, 90)
      prod(ijk, 30) = + w(ijk, 94)
      prod(ijk, 31) = + w(ijk, 95)
      END DO   
                                                                                
   END SUBROUTINE fexprod                                                       
                                                                                
  END MODULE mod_chem_spack_fexprod                                             
                                                                                
