                                                                                
 MODULE mod_chem_spack_fexchem                                                  
                                                                                
   USE mod_chem_spack_rates, ONLY: rates  ! subroutine                          
   IMPLICIT NONE                                                                
   PRIVATE                                                                      
   PUBLIC :: fexchem ! subroutine                                               
 CONTAINS                                                                       
                                                                                
   SUBROUTINE fexchem(y,rk,chem,ngas,ijkbegin,ijkend,maxblock_size,nr)          
                                                                                
!------------------------------------------------------------------------       
!                                                                               
!     -- DESCRIPTION                                                            
!                                                                               
!     This routine computes the chemical production term.                       
!     This routine is automatically generated by SPACK.                         
!     Mechanism: ../Mechanism/HETEST                                            
!     Species: ../Mechanism/ciHETR                                              
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- INPUT VARIABLES                                                        
!                                                                               
!     Y: chemical concentrations.                                               
!     RK: kinetic rates.                                                        
!     ZCSOURC: volumic emissions.                                               
!                                                                               
!     -- INPUT/OUTPUT VARIABLES                                                 
!                                                                               
!     -- OUTPUT VARIABLES                                                       
!                                                                               
!     CHEM: array of chemical production terms.                                 
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- REMARKS                                                                
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- MODIFICATIONS                                                          
!                                                                               
!------------------------------------------------------------------------       
!                                                                               
!     -- AUTHOR(S)                                                              
!                                                                               
!     SPACK.                                                                    
!                                                                               
!------------------------------------------------------------------------       
                                                                                
       IMPLICIT NONE                                                            
                                                                                
                                                                                
      INTEGER  	, INTENT(IN)  :: ngas                                           
      INTEGER  	, INTENT(IN)  :: ijkbegin		                                     
      INTEGER  	, INTENT(IN)  :: ijkend 		                                      
      INTEGER  	, INTENT(IN)  :: maxblock_size		                                
      INTEGER  	, INTENT(IN)  :: nr		  	                                        
      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)	                   
      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,ngas)                   
      DOUBLE PRECISION , INTENT(OUT) :: chem(maxblock_size,NGAS)                
      DOUBLE PRECISION :: w(maxblock_size,nr)			                                
      INTEGER ::  ijk						                                                     
                                                                                
                                                                                
!     Compute reaction rates.                                                   
                                                                                
      call rates(rk,y,w,ngas,ijkbegin,ijkend,maxblock_size,nr)                  
                                                                                
!     Chemical production terms.                                                
                                                                                
                                                                                
      DO ijk=ijkbegin,ijkend                                                    
      chem(ijk,  1) = - w(ijk,  2) &
          - w(ijk,  3) &
          + w(ijk, 20) &
          - w(ijk, 21) &
          - w(ijk, 26) &
          - w(ijk, 27) &
          - w(ijk, 45) &
          - w(ijk, 46) &
          - w(ijk, 65) &
          - w(ijk, 86)
      chem(ijk,  2) = + w(ijk, 10) &
          - w(ijk, 25) &
          - w(ijk, 53)
      chem(ijk,  3) = - w(ijk,  9) &
          - w(ijk, 29) &
          + w(ijk, 30) &
          + w(ijk, 31)
      chem(ijk,  4) = + w(ijk,  1) &
          + w(ijk,  4) &
          + w(ijk,  7) &
          - w(ijk, 32) &
          + w(ijk, 33) &
          - w(ijk, 35) &
          - w(ijk, 38) &
          - w(ijk, 45) &
          -  0.2000000000000000D+01 * w(ijk, 47) &
          - w(ijk, 48) &
          + w(ijk, 49) &
          - w(ijk, 59) &
          - w(ijk, 66) &
          - w(ijk, 88)
      chem(ijk,  5) = - w(ijk,  1) &
          + w(ijk,  5) &
          + w(ijk,  6) &
          + w(ijk,  8) &
          + w(ijk, 14) &
          + w(ijk, 32) &
          - w(ijk, 33) &
          - w(ijk, 34) &
          - w(ijk, 36) &
          + w(ijk, 37) &
          + w(ijk, 38) &
          - w(ijk, 39) &
          + w(ijk, 40) &
          +  0.7000000000000000D+00 * w(ijk, 41) &
          + w(ijk, 42) &
          + w(ijk, 44) &
          + w(ijk, 45) &
          - w(ijk, 46) &
          +  0.2000000000000000D+01 * w(ijk, 47) &
          +  0.2000000000000000D+01 * w(ijk, 48) &
          - w(ijk, 50) &
          + w(ijk, 51) &
          +  0.2000000000000000D+01 * w(ijk, 52) &
          + w(ijk, 59) &
          + w(ijk, 62) &
          + w(ijk, 64) &
          + w(ijk, 66) &
          - w(ijk, 75) &
          + w(ijk, 88) &
          - w(ijk, 94)
      chem(ijk,  6) = - w(ijk,  7) &
          - w(ijk,  8) &
          + w(ijk, 13) &
          + w(ijk, 18) &
          + w(ijk, 34) &
          - w(ijk, 37) &
          - w(ijk, 41) &
          + w(ijk, 43) &
          + w(ijk, 46) &
          - w(ijk, 48) &
          - w(ijk, 49) &
          - w(ijk, 50) &
          + w(ijk, 51) &
          -  0.2000000000000000D+01 * w(ijk, 52) &
          - w(ijk, 58) &
          - w(ijk, 62) &
          + w(ijk, 84)
      chem(ijk,  7) = + w(ijk, 50) &
          - w(ijk, 51)
      chem(ijk,  8) = - w(ijk,  4) &
          + w(ijk, 35) &
          - w(ijk, 42)
      chem(ijk,  9) = - w(ijk,  5) &
          + w(ijk, 36) &
          +  0.3000000000000000D+00 * w(ijk, 41) &
          - w(ijk, 43) &
          + w(ijk, 58)
      chem(ijk, 10) = - w(ijk,  6) &
          + w(ijk, 39) &
          - w(ijk, 40) &
          - w(ijk, 44)
      chem(ijk, 11) = + w(ijk, 10) &
          + w(ijk, 11) &
          - w(ijk, 54) &
          + w(ijk, 56) &
          + w(ijk, 58) &
          + w(ijk, 63) &
          + w(ijk, 85)
      chem(ijk, 12) = + w(ijk,  1) &
          + w(ijk,  3) &
          + w(ijk,  8) &
          + w(ijk, 17) &
          - w(ijk, 20) &
          - w(ijk, 21) &
          + w(ijk, 22) &
          + w(ijk, 23) &
          - w(ijk, 32) &
          - w(ijk, 33) &
          - w(ijk, 34) &
          - w(ijk, 67) &
          - w(ijk, 78) &
          - w(ijk, 84) &
          - w(ijk, 87) &
          - w(ijk, 96)
      chem(ijk, 13) = + w(ijk,  2) &
          - w(ijk, 22) &
          - w(ijk, 23) &
          - w(ijk, 24) &
          - w(ijk, 25) &
          - w(ijk, 91)
      chem(ijk, 14) = + w(ijk,  4) &
          + w(ijk,  5) &
          +  0.2000000000000000D+01 * w(ijk,  9) &
          + w(ijk, 12) &
          + w(ijk, 19) &
          +  0.2000000000000000D+01 * w(ijk, 24) &
          + w(ijk, 25) &
          - w(ijk, 26) &
          + w(ijk, 27) &
          - w(ijk, 28) &
          - w(ijk, 29) &
          - w(ijk, 35) &
          - w(ijk, 36) &
          - w(ijk, 37) &
          + w(ijk, 38) &
          +  0.7000000000000000D+00 * w(ijk, 41) &
          - w(ijk, 42) &
          - w(ijk, 43) &
          - w(ijk, 44) &
          - w(ijk, 53) &
          - w(ijk, 54) &
          - w(ijk, 55) &
          - w(ijk, 56) &
          -  0.6500000000000000D+00 * w(ijk, 57) &
          + w(ijk, 71) &
          - w(ijk, 72) &
          - w(ijk, 73) &
          - w(ijk, 74) &
          - w(ijk, 77) &
          + w(ijk, 78) &
          + w(ijk, 79) &
          + w(ijk, 91) &
          - w(ijk, 92) &
          - w(ijk, 93) &
          + w(ijk, 96)
      chem(ijk, 15) = + w(ijk,  6) &
          +  0.2000000000000000D+01 * w(ijk, 11) &
          + w(ijk, 12) &
          + w(ijk, 25) &
          + w(ijk, 26) &
          - w(ijk, 27) &
          - w(ijk, 28) &
          + w(ijk, 29) &
          -  0.2000000000000000D+01 * w(ijk, 30) &
          -  0.2000000000000000D+01 * w(ijk, 31) &
          + w(ijk, 37) &
          - w(ijk, 38) &
          - w(ijk, 39) &
          + w(ijk, 40) &
          - w(ijk, 41) &
          + w(ijk, 53) &
          + w(ijk, 54) &
          + w(ijk, 56) &
          + w(ijk, 58) &
          + w(ijk, 59) &
          - w(ijk, 60) &
          +  0.6600000000000000D+00 * w(ijk, 61) &
          + w(ijk, 62) &
          + w(ijk, 63) &
          - w(ijk, 70) &
          - w(ijk, 71) &
          + w(ijk, 72) &
          - w(ijk, 76) &
          + w(ijk, 85) &
          - w(ijk, 90) &
          + w(ijk, 92) &
          - w(ijk, 95)
      chem(ijk, 16) = - w(ijk, 55) &
          - w(ijk, 68)
      chem(ijk, 17) = - w(ijk, 10) &
          - w(ijk, 11) &
          + w(ijk, 12) &
          - w(ijk, 56) &
          +  0.3500000000000000D+00 * w(ijk, 57) &
          - w(ijk, 58) &
          + w(ijk, 59) &
          +  0.1330000000000000D+01 * w(ijk, 61) &
          + w(ijk, 62) &
          - w(ijk, 63) &
          + w(ijk, 64) &
          - w(ijk, 85)
      chem(ijk, 18) = - w(ijk, 12) &
          - w(ijk, 57) &
          + w(ijk, 60)
      chem(ijk, 19) = + w(ijk, 55) &
          +  0.6500000000000000D+00 * w(ijk, 57) &
          - w(ijk, 59) &
          - w(ijk, 60) &
          -  0.2000000000000000D+01 * w(ijk, 61) &
          - w(ijk, 62) &
          - w(ijk, 64) &
          + w(ijk, 68)
      chem(ijk, 20) = + w(ijk, 13) &
          +  0.2000000000000000D+01 * w(ijk, 15) &
          +  0.2000000000000000D+01 * w(ijk, 16) &
          - w(ijk, 63) &
          + w(ijk, 64) &
          - w(ijk, 65) &
          + w(ijk, 66) &
          + w(ijk, 67) &
          - w(ijk, 68) &
          - w(ijk, 69) &
          - w(ijk, 70) &
          - w(ijk, 71) &
          + w(ijk, 72) &
          + w(ijk, 74) &
          - w(ijk, 79)
      chem(ijk, 21) = + w(ijk, 63) &
          + w(ijk, 68) &
          + w(ijk, 69) &
          + w(ijk, 70) &
          + w(ijk, 73) &
          - w(ijk, 74)
      chem(ijk, 22) = + w(ijk, 14) &
          - w(ijk, 64) &
          + w(ijk, 65) &
          - w(ijk, 66) &
          - w(ijk, 67) &
          + w(ijk, 71) &
          - w(ijk, 72) &
          - w(ijk, 73) &
          - w(ijk, 75) &
          - w(ijk, 76) &
          + w(ijk, 77) &
          + w(ijk, 78) &
          -  0.2000000000000000D+01 * w(ijk, 80) &
          +  0.2000000000000000D+01 * w(ijk, 81) &
          -  0.2000000000000000D+01 * w(ijk, 82) &
          -  0.2000000000000000D+01 * w(ijk, 83) &
          + w(ijk, 84)
      chem(ijk, 23) = - w(ijk, 13) &
          - w(ijk, 14) &
          + w(ijk, 75) &
          - w(ijk, 84)
      chem(ijk, 24) = + w(ijk, 76) &
          - w(ijk, 77) &
          - w(ijk, 78) &
          - w(ijk, 79)
      chem(ijk, 25) = - w(ijk, 15) &
          + w(ijk, 80) &
          - w(ijk, 81)
      chem(ijk, 26) = - w(ijk, 16) &
          + w(ijk, 79) &
          + w(ijk, 82) &
          + w(ijk, 83)
      chem(ijk, 27) = - w(ijk, 17) &
          + w(ijk, 86) &
          - w(ijk, 87) &
          - w(ijk, 88) &
          -  0.2000000000000000D+01 * w(ijk, 89) &
          - w(ijk, 92) &
          - w(ijk, 94) &
          - w(ijk, 95) &
          + w(ijk, 96)
      chem(ijk, 28) = + w(ijk, 17) &
          + w(ijk, 18) &
          + w(ijk, 19) &
          - w(ijk, 85) &
          - w(ijk, 86) &
          + w(ijk, 87) &
          + w(ijk, 88) &
          +  0.2000000000000000D+01 * w(ijk, 89) &
          - w(ijk, 90) &
          + w(ijk, 91) &
          + w(ijk, 92) &
          + w(ijk, 93)
      chem(ijk, 29) = + w(ijk, 85) &
          + w(ijk, 90) &
          - w(ijk, 91) &
          - w(ijk, 93)
      chem(ijk, 30) = - w(ijk, 18) &
          + w(ijk, 94)
      chem(ijk, 31) = - w(ijk, 19) &
          + w(ijk, 95) &
          - w(ijk, 96)
      END DO   
                                                                                
!     Volumic source terms.                                                     
                                                                                
                                                                                
   END SUBROUTINE fexchem                                                       
                                                                                
  END MODULE mod_chem_spack_fexchem                                             
                                                                                
