module ModWrite
    implicit none

contains

    subroutine write_header(ntuvonline)
       !------------------------------------------------------------------------

       !     -- DESCRIPTION

       !     Write headers of subroutines

       !     FEXCHEM.F    : chemical production terms (P-Lc).
       !     JACDCHEMDC.F : Jacobian Matrix (d/dc(P-Lc)).
       !     KINETIC.F    : kinetic rate k.
       !     RATES.F      : reaction rates w.
       !     DRATEDC.F    : derivatives dw/dc.
       !     FEXPROD.F    : production terms P.
       !     FEXLOSS.F    : loss terms L.
       !------------------------------------------------------------------------

       !     -- INPUT VARIABLES

       !     -- INPUT/OUTPUT VARIABLES

       !     -- OUTPUT VARIABLES

       !------------------------------------------------------------------------

       !     -- REMARKS

       !     Label 300: blank line.
       !     Label 150: comments.
       !     Label 200: C-------...
       !------------------------------------------------------------------------

       !     -- MODIFICATIONS
       !     Rodrigues, L.F., INPE, 2026. luflarois@gmail.com
       !     Converted to Fortran90 and using modules for better code organization 
       !     and maintainability. Useless variables and common blocks have been removed, 
       !     and the code has been  restructured to improve readability and efficiency.

       !------------------------------------------------------------------------

       !     -- AUTHOR(S)

       !     Bruno Sportisse, CEREA, 2003.

       !------------------------------------------------------------------------
       use ModParametre
       use ModNficfort, only: ipiste, filemeca, filespecies, nfick, nficdw, nficf &
                              , nficj, nficnz, nficloss, nficprod, nficw
       implicit none


       integer, intent(in) :: ntuvonline

       integer :: nwrite

       !------------------------------------------------------------------------------------------------

       !     Routine kinetic.f90
       nfick = ipiste
       ipiste = ipiste + 1
       open(nfick, file = 'chem_spack_kinetic.f90', status = 'new')
       nwrite = nfick

       !srf - for modules format
       write(nwrite, 6701)
       6701 format(1x, 'MODULE mod_chem_spack_kinetic')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6705)
       6705 format(3x, 'PUBLIC :: kinetic ! subroutine')
       write(nwrite, 6006)
       !srf- sempre colocar cosz no argumento rotina kinetic para man
       write(nwrite, 401)

       401 format(3x, 'SUBROUTINE kinetic(jppj,Jphoto,rk,temp,xlw,Press,cosz,att,ijkbeg,ijkend,maxblock_size,nr)')

       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 402)
       402 format('!', 5x, '-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 403)
       403 format('!', 5x, 'This routine computes the kinetic rates', &
       ' for the gas-phase.')
       write(nwrite, 404)
       404 format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       250 format('!     Mechanism: ', a20)
       251 format('!     Species: ', a20)
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 405)
       405 format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 406)
       406 format('!     TEMP: temperature ([K]).')
       write(nwrite, 407)
       407 format('!     XLW: water massic fraction.')
       write(nwrite, 408)
       408 format('!     PRESS: pressure ([Pa]).')
       if (ntuvonline == 0) write(nwrite, 409)
       409 format('!     AZI: zenithal angle ([degree]).')
       write(nwrite, 410)
       410 format('!     ATT: attenuation variable.')
       write(nwrite, 150)
       write(nwrite, 413)
       413 format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 414)
       414 format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 415)
       415 format('!     RK: kinetic rates.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 416)
       416 format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 417)
       417 format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 418)
       418 format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 419)
       419 format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       !srf- nr is now passed via argument of the command call
       !WRITE(nwrite,FMT='(A)') '  USE chem1_list, ONLY: nr'
       write(nwrite, 300)
       write(nwrite, 420)
       420 format('      IMPLICIT NONE')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      INTEGER,INTENT(IN) :: jppj,ijkbeg,ijkend,maxblock_size,nr'
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,INTENT(IN) ::  xlw(maxblock_size),att(maxblock_size),cosz(maxblock_size)'
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,INTENT(IN) ::  temp(maxblock_size),Press(maxblock_size)'
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,INTENT(OUT) ::  rk(maxblock_size,nr)'

       if (ntuvonline == 0) then
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur'
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi'
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)'
       else
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur'
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi'
          write(nwrite, fmt = '(A)') '      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)'
       end if
       write(nwrite, fmt = '(A)') '      INTEGER :: ijk'

       write(nwrite, 300)
       write(nwrite, 438)
       438 format('!     Compute third body.')
       write(nwrite, 439)
       439 format('!     Conversion = Avogadro*1d-6/Perfect gas constant.')
       write(nwrite, 440)
       440 format('!     PRESS in Pascal, SUMM in molecules/cm3,', &
       ' TEMP in Kelvin')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbeg,ijkend'
       write(nwrite, fmt = '(A)') '        SumM(ijk) = Press(ijk) * 7.243D16 / temp(ijk)'
       write(nwrite, fmt = '(A)') '      END DO'
       write(nwrite, 300)
       write(nwrite, 442)
       442 format('!     Number of water molecules computed from', &
       ' the massic fraction')
       write(nwrite, 443)
       443 format('!     (absolute humidity)')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbeg,ijkend'
       write(nwrite, fmt = '(A)') '         YlH2O(ijk) = 29.d0*SumM(ijk)*xlw(ijk)/(18.d0+11.d0*xlw(ijk))'
       write(nwrite, fmt = '(A)') '      END DO'
       write(nwrite, 300)
       write(nwrite, 445)
       445 format('!     For the zenithal angle at tropics')
       write(nwrite, 300)
       if (ntuvonline == 0) write(nwrite, 446)
       446 format('      azi=abs(acos(cosz)*180.0/3.1415926) !From cosz obtain angle azi in degrees')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '       DO ijk=ijkbeg,ijkend'


       !------------------------------------------------------------------------------------------------
       !     Routine fexchem.f90
       nficf = ipiste
       ipiste = ipiste + 1
       open(nficf, file = 'chem_spack_fexchem.f90', status = 'new')
       nwrite = nficf
       write(nwrite, fmt = '(A)') '  '
       !srf - for modules format
       write(nwrite, 6501)
       6501 format(1x, 'MODULE mod_chem_spack_fexchem')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6502)
       6502 format(3x, 'USE mod_chem_spack_rates, ONLY: rates  ! subroutine')

       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6505)
       6505 format(3x, 'PUBLIC :: fexchem ! subroutine')
       write(nwrite, 6006)

       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 501)
       501 format(3x, 'SUBROUTINE fexchem(y,rk,chem,ngas,ijkbegin,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 502)
       502 format('!', 5x, '-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 503)
       503 format('!', 5x, 'This routine computes the chemical production', ' term.')
       write(nwrite, 504)
       504 format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 505)
       505 format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 506)
       506 format('!     Y: chemical concentrations.')
       write(nwrite, 415)
       !     415  format('!     RK: kinetic rates.')
       507 format('!     W: reaction rates.')
       write(nwrite, 508)
       508 format('!     ZCSOURC: volumic emissions.')
       write(nwrite, 150)
       write(nwrite, 513)
       513 format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 514)
       514 format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 515)
       515 format('!     CHEM: array of chemical production terms.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 516)
       516 format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 517)
       517 format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 518)
       518 format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 519)
       519 format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '       IMPLICIT NONE'
       write(nwrite, 300)
       write(nwrite, 300)

       !WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbegin,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '      LOGICAL,INTENT(IN) :: lsourc !Volumic source terms'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: rk(maxblock_size,nr)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: y(maxblock_size,ngas)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: ZCsourc(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(OUT) :: chem(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION :: w(maxblock_size,nr)'
       !WRITE(nwrite,FMT='(A)') '      INTEGER ::  i,ijk'

       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ngas                    '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkbegin       '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkend        '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: maxblock_size       '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: nr            '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)    '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,ngas)   '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(OUT) :: chem(maxblock_size,NGAS)'
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION :: w(maxblock_size,nr)          '
       write(nwrite, fmt = '(A)') '      INTEGER ::  ijk                   '


       write(nwrite, 300)
       write(nwrite, 539)
       539 format('       chem=0.d0')
       write(nwrite, 300)
       write(nwrite, 541)
       541 format('!     Compute reaction rates.')
       write(nwrite, 300)
       write(nwrite, 542)
       542 format('      call rates(rk,y,w,ngas,ijkbegin,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 543)
       543 format('!     Chemical production terms.')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbegin,ijkend'




       !------------------------------------------------------------------------------------------------
       !     Routine jacdchemdc.f90
       nficj = ipiste
       ipiste = ipiste + 1
       open(nficj, file = 'chem_spack_jacdchemdc.f90', status = 'new')
       nwrite = nficj
       write(nwrite, fmt = '(A)') '  '

       !srf - for modules format
       write(nwrite, 6001)
       6001 format(1x, 'MODULE mod_chem_spack_jacdchemdc')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6002)
       6002 format(3x, 'USE mod_chem_spack_dratedc, ONLY: dratedc  ! subroutine')
       write(nwrite, 6003)
       6003 format(3x, 'IMPLICIT NONE')
       write(nwrite, 6004)
       6004 format(3x, 'PRIVATE')
       write(nwrite, 6005)
       6005 format(3x, 'PUBLIC :: jacdchemdc ! subroutine')
       write(nwrite, 6006)
       6006 format(1x, 'CONTAINS')
       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 601)
       601 format(3x, 'SUBROUTINE jacdchemdc(y,rk,JacC,ngas,ijkbeg,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 602)
       602 format('!', 5x, '-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 603)
       603 format('!', 5x, 'This routine computes the Jacobian matrix', &
       ' for the gas-phase.')
       write(nwrite, 604)
       604 format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 605)
       605 format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 606)
       606 format('!     Y: chemical concentrations.')
       write(nwrite, 415)
       !     415  format('!     RK: kinetic rates.')
       607 format('!     DW: derivative of reaction rates wrt Y.')
       write(nwrite, 150)
       write(nwrite, 613)
       613 format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 614)
       614 format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 615)
       615 format('!     JACC: Jacobian matrix.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 616)
       616 format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 609)
       609 format('!     The matrix JACC could be stored in a ', &
       'low-dimensional vector.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 617)
       617 format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 618)
       618 format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 619)
       619 format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       write(nwrite, 620)
       620 format('      IMPLICIT NONE')
       write(nwrite, 300)

       write(nwrite, 300)
       !WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(OUT) :: JacC(maxblock_size,NGAS,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION :: dw(maxblock_size,nr,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      INTEGER :: i,j,ijk'


       write(nwrite, fmt = '(A)') '       INTEGER     , INTENT(IN)  :: ngas                          '
       write(nwrite, fmt = '(A)') '       INTEGER     , INTENT(IN)  :: ijkbeg         '
       write(nwrite, fmt = '(A)') '       INTEGER     , INTENT(IN)  :: ijkend         '
       write(nwrite, fmt = '(A)') '       INTEGER     , INTENT(IN)  :: maxblock_size       '
       write(nwrite, fmt = '(A)') '       INTEGER     , INTENT(IN)  :: nr             '
       write(nwrite, fmt = '(A)') '       DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)      '
       write(nwrite, fmt = '(A)') '       DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS)    '
       write(nwrite, fmt = '(A)') '       DOUBLE PRECISION , INTENT(OUT) :: JacC(maxblock_size,NGAS,NGAS) '
       write(nwrite, fmt = '(A)') '                               '
       write(nwrite, fmt = '(A)') '       DOUBLE PRECISION :: dw(maxblock_size,nr,NGAS)         '
       write(nwrite, fmt = '(A)') '       INTEGER :: ijk                     '

       write(nwrite, 300)
       write(nwrite, 637)
       637 format('        JacC=0.d0')
       write(nwrite, 300)
       write(nwrite, 640)
       640 format('      CALL dratedc(rk,y,dw,ngas,ijkbeg,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbeg,ijkend'


       !-------------------------------------------------------------------------------------------

       !     Routine fexloss.f90
       nficloss = ipiste
       ipiste = ipiste + 1
       open(nficloss, file = 'chem_spack_fexloss.f90', status = 'new')
       nwrite = nficloss
       write(nwrite, fmt = '(A)') '  '
       !srf - for modules format
       write(nwrite, 6101)
       6101 format(1x, 'MODULE mod_chem_spack_fexloss')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6105)
       6105 format(3x, 'PUBLIC :: fexloss ! subroutine')
       write(nwrite, 6006)

       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 701)
       701 format(3x, 'SUBROUTINE fexloss(dw,loss,ngas,ijkbegin,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 502)
       !     502  format('!',5x,'-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 703)
       703 format('!', 5x, 'This routine computes the chemical loss ', &
       ' term L in a P-Lc formulation.')
       write(nwrite, 504)
       !     504  format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 505)
       !     505  format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 607)
       !     607  format('!     DW: derivative of reaction rates wrt Y.')
       write(nwrite, 150)
       write(nwrite, 513)
       !     513  format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 514)
       !     514  format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 715)
       715 format('!     LOSS: array of chemical loss terms.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 516)
       !     516  format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 517)
       !     517  format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 518)
       !     518  format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 519)
       !     519  format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       !      write(nwrite,520)
       !     520  format('      implicit none')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '       IMPLICIT NONE'
       write(nwrite, 300)

       !WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: NGAS,ijkbegin,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(IN)  :: dw(maxblock_size,nr,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(OUT) :: loss(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk'

       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: NGAS                       '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: ijkbegin          '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: ijkend             '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: maxblock_size          '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: nr              '
       write(nwrite, fmt = '(A)') '     DOUBLE PRECISION , INTENT(IN)  :: dw(maxblock_size,nr,NGAS)   '
       write(nwrite, fmt = '(A)') '     DOUBLE PRECISION , INTENT(OUT) :: loss(maxblock_size,NGAS)    '
       write(nwrite, fmt = '(A)') '     INTEGER :: ijk                      '

       write(nwrite, fmt = '(A)') ''
       write(nwrite, fmt = '(A)') '       loss=0.d0'

       write(nwrite, 300)
       write(nwrite, 741)
       741 format('!     Chemical loss terms.')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbegin,ijkend'

       !--------------------------------------------------------------------------------
       !     Routine fexprod.f90
       nficprod = ipiste
       ipiste = ipiste + 1
       open(nficprod, file = 'chem_spack_fexprod.f90', status = 'new')
       nwrite = nficprod
       write(nwrite, fmt = '(A)') '  '

       !srf - for modules format
       write(nwrite, 6201)
       6201 format(1x, 'MODULE mod_chem_spack_fexprod')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6205)
       6205 format(3x, 'PUBLIC :: fexprod ! subroutine')
       write(nwrite, 6006)


       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 801)
       801 format(3x, 'SUBROUTINE fexprod(w,prod,ngas,ijkbegin,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 502)
       !     502  format('!',5x,'-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 803)
       803 format('!', 5x, 'This routine computes the production ', &
       ' term P in a P-Lc formulation.')
       write(nwrite, 504)
       !     504  format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 505)
       !     505  format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 507)
       !     507  format('!     W: reaction rates.')
       write(nwrite, 150)
       write(nwrite, 513)
       !     513  format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 514)
       !     514  format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 815)
       815 format('!     PROD: array of chemical production terms.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 516)
       !     516  format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 517)
       !     517  format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 518)
       !     518  format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 519)
       !     519  format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       !      write(nwrite,520)
       !     520  format('      implicit none')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '       IMPLICIT NONE'

       write(nwrite, 300)

       !WRITE(nwrite,FMT='(A)') '  INTEGER,INTENT(IN) :: ngas,ijkbegin,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '  DOUBLE PRECISION,INTENT(IN) :: w(maxblock_size,nr)'
       !WRITE(nwrite,FMT='(A)') '  DOUBLE PRECISION,INTENT(OUT) :: prod(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '  INTEGER :: ijk'

       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ngas                      '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkbegin         '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkend          '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: maxblock_size         '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: nr                  '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(IN)  :: w(maxblock_size,nr)      '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(OUT) :: prod(maxblock_size,NGAS)  '
       write(nwrite, fmt = '(A)') '      INTEGER :: ijk                     '

       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '       prod=0.d0'
       write(nwrite, 300)
       write(nwrite, 841)
       841 format('!     Chemical production terms.')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbegin,ijkend'

       !--------------------------------------------------------------------------------
       !     Routine rates.f90
       nficw = ipiste
       ipiste = ipiste + 1
       open(nficw, file = 'chem_spack_rates.f90', status = 'new')
       nwrite = nficw
       write(nwrite, fmt = '(A)') '  '

       !srf - for modules format
       write(nwrite, 6301)
       6301 format(1x, 'MODULE mod_chem_spack_rates')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6305)
       6305 format(3x, 'PUBLIC :: rates ! subroutine')
       write(nwrite, 6006)


       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 901)
       901 format(3x, 'SUBROUTINE rates(rk,y,w,ngas,ijkbeg,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 502)
       !     502  format('!',5x,'-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 902)
       902 format('!', 5x, 'This routine computes the reaction rates.')
       write(nwrite, 504)
       !     504  format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 505)
       !     505  format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 903)
       903 format('!     RK: kinetic rates.')
       write(nwrite, 506)
       !     506  format('!     Y: chemical concentrations.')
       write(nwrite, 150)
       write(nwrite, 513)
       !     513  format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 514)
       !     514  format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 507)
       !     507  format('!     W: reaction rates.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 516)
       !     516  format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 517)
       !     517  format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 518)
       !     518  format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 519)
       !     519  format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       write(nwrite, 520)
       520 format('      IMPLICIT NONE')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, 300)
       !WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS)'
       !WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(OUT) :: w(maxblock_size,nr)'
       !WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk'


       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ngas                  '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkbeg           '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: ijkend           '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: maxblock_size          '
       write(nwrite, fmt = '(A)') '      INTEGER     , INTENT(IN)  :: nr             '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)  '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS) '
       write(nwrite, fmt = '(A)') '      DOUBLE PRECISION , INTENT(OUT) :: w(maxblock_size,nr)   '
       write(nwrite, fmt = '(A)') '      INTEGER                   :: ijk             '

       !     write(nwrite,537)
       !     537  format('      integer i')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '      DO ijk=ijkbeg,ijkend'

       !-----------------------------------------------------------------------------
       !     Routine dratedc.f
       nficdw = ipiste
       ipiste = ipiste + 1
       open(nficdw, file = 'chem_spack_dratedc.f90', status = 'new')
       nwrite = nficdw
       write(nwrite, fmt = '(A)') '  '


       !srf - for modules format
       write(nwrite, 6401)
       6401 format(1x, 'MODULE mod_chem_spack_dratedc')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, 6003)
       write(nwrite, 6004)
       write(nwrite, 6405)
       6405 format(3x, 'PUBLIC :: dratedc ! subroutine')
       write(nwrite, 6006)

       write(nwrite, fmt = '(A)') '  '

       write(nwrite, 910)
       910 format(3x, 'SUBROUTINE dratedc(rk,y,dw,ngas,ijkbeg,ijkend,maxblock_size,nr)')
       write(nwrite, 300)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 502)
       !     502  format('!',5x,'-- DESCRIPTION')
       write(nwrite, 150)
       write(nwrite, 911)
       911 format('!', 5x, 'This routine computes the derivative of reaction ', &
       ' rates.')
       write(nwrite, 504)
       !     504  format('!     This routine is automatically generated by SPACK.')
       write(nwrite, 250) filemeca
       write(nwrite, 251) filespecies
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 505)
       !     505  format('!     -- INPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 903)
       !     903  format('!     RK: kinetic rates.')
       write(nwrite, 506)
       !     506  format('!     Y: chemical concentrations.')
       write(nwrite, 150)
       write(nwrite, 513)
       !     513  format('!     -- INPUT/OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 514)
       !     514  format('!     -- OUTPUT VARIABLES')
       write(nwrite, 150)
       write(nwrite, 607)
       !     607  format('!     DW: derivative of reaction rates wrt Y.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 516)
       !     516  format('!     -- REMARKS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 517)
       !     517  format('!     -- MODIFICATIONS')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 150)
       write(nwrite, 518)
       !     518  format('!     -- AUTHOR(S)')
       write(nwrite, 150)
       write(nwrite, 519)
       !     519  format('!     SPACK.')
       write(nwrite, 150)
       write(nwrite, 200)
       write(nwrite, 300)
       write(nwrite, 520)
       !520  format('      IMPLICIT NONE')
       write(nwrite, 300)
       write(nwrite, 300)
       write(nwrite, 300)

       !WRITE(nwrite,FMT='(A)') '     INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr'
       !WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION,INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS) '
       !WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION,INTENT(OUT) :: dw(maxblock_size,nr,NGAS) '
       !WRITE(nwrite,FMT='(A)') '     INTEGER :: ijk'
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: ngas                      '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: ijkbeg           '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: ijkend           '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: maxblock_size        '
       write(nwrite, fmt = '(A)') '     INTEGER          , INTENT(IN)  :: nr           '
       write(nwrite, fmt = '(A)') '     DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)     '
       write(nwrite, fmt = '(A)') '     DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS)      '
       write(nwrite, fmt = '(A)') '     DOUBLE PRECISION , INTENT(OUT) :: dw(maxblock_size,nr,NGAS) '
       write(nwrite, fmt = '(A)') '     INTEGER :: ijk                    '

       !     write(nwrite,537)
       !     537  format('      integer i')
       write(nwrite, 300)
       write(nwrite, fmt = '(A)') '     DO ijk=ijkbeg,ijkend'
       !     File non_zero.dat
       nficnz = ipiste
       ipiste = ipiste + 1
       open(nficnz, file = 'non_zero.dat', status = 'new')
       write(nwrite, fmt = '(A)') '  '
       write(nwrite, fmt = '(A)') '  '

       150 format('!', 6x, a65)
       200 format('!-----------------------------------', &
       '-------------------------------------')
       300 format(' ')

       111 format('!      INCLUDE FILES only for CATT-BRAMS!!!! ')
       222 format('      INCLUDE ''PARAMETRE'' ')
       333 format('      INCLUDE ''FICCOM'' ')
       555 format('      INCLUDE ''TUV.H'' ')


       return
    end subroutine write_header

   subroutine write_end
      !------------------------------------------------------------------------

      !     -- DESCRIPTION

      !     Write end of subroutines fexchem.f90, jacdchemdc.f90 and kinetic.f90.
      !------------------------------------------------------------------------

      !     -- INPUT VARIABLES

      !     -- INPUT/OUTPUT VARIABLES

      !     -- OUTPUT VARIABLES

      !------------------------------------------------------------------------

      !     -- REMARKS

      !     Label 300: blank line.
      !     Label 150: comments.
      !     Label 200: C-------...
      !------------------------------------------------------------------------

       !     -- MODIFICATIONS
       !     Rodrigues, L.F., INPE, 2026. luflarois@gmail.com
       !     Converted to Fortran90 and using modules for better code organization 
       !     and maintainability. Useless variables and common blocks have been removed, 
       !     and the code has been  restructured to improve readability and efficiency.

      !------------------------------------------------------------------------

      !     -- AUTHOR(S)

      !     Bruno Sportisse, CEREA, 2003.

      !------------------------------------------------------------------------
      use ModNficfort, only: nficf, nfick, nficj, nficloss, nficprod, nficw, nficdw
      implicit none

      integer :: nwrite
      !     Routine fexchem.f90
      nwrite = nficf

      write(nwrite, fmt = '(A)') '      END DO'
      write(nwrite, 300)
      write(nwrite, 101)
      101 format('!     Volumic source terms.')
      write(nwrite, 300)
      !WRITE(nwrite,FMT='(A)') '        IF(LSOURC)THEN'
      !WRITE(nwrite,FMT='(A)') '         chem=chem+ZCsourc'
      !WRITE(nwrite,FMT='(A)') '      END IF'
      call write_end2(nwrite)
      !     Routine kinetic.f90
      nwrite = nfick
      call write_end2(nwrite)

      !     Routine jacdchemdc.f90
      nwrite = nficj
      call write_end2(nwrite)

      !     Routine fexloss.f90
      nwrite = nficloss
      call write_end2(nwrite)

      !     Routine fexprod.f90
      nwrite = nficprod
      call write_end2(nwrite)

      !     Routine rates.f90
      nwrite = nficw
      call write_end2(nwrite)

      !     Routine dratedc.f90
      nwrite = nficdw
      call write_end2(nwrite)



      150 format('!', 6x, a65)
      200 format('!-----------------------------------', &
      '-------------------------------------')
      300 format(' ')
      110 format(6x, 'END SUBROUTINE')

   end subroutine write_end

   subroutine write_end2(nwrite)
      use ModNficfort, only: nficf, nfick, nficj, nficloss, nficprod, nficw, nficdw
      implicit none

      integer, intent(in) :: nwrite
      character(len = 10) :: cnsub

      if (nwrite == nficdw) cnsub = 'dratedc'
      if (nwrite == nficw) cnsub = 'rates'
      if (nwrite == nficprod) cnsub = 'fexprod'
      if (nwrite == nficloss) cnsub = 'fexloss'
      if (nwrite == nficj) cnsub = 'jacdchemdc'
      if (nwrite == nfick) cnsub = 'kinetic'
      if (nwrite == nficf) cnsub = 'fexchem'

      if (nwrite == nfick) write(nwrite, fmt = '(A)') '       END DO'
      if (nwrite == nficj) write(nwrite, fmt = '(A)') '       END DO'
      if (nwrite == nficw) write(nwrite, fmt = '(A)') '       END DO'
      if (nwrite == nficdw) write(nwrite, fmt = '(A)') '       END DO'
      if (nwrite == nficprod) write(nwrite, fmt = '(A)') '      END DO'
      if (nwrite == nficloss) write(nwrite, fmt = '(A)') '      END DO'
      write(nwrite, 300)
      write(nwrite, fmt = '(A)') '   END SUBROUTINE ' // trim(cnsub)
      write(nwrite, 300)
      write(nwrite, fmt = '(A)') '  END MODULE mod_chem_spack_' // trim(cnsub)
      write(nwrite, 300)

      150 format('!', 6x, a65)
      200 format('!-----------------------------------', &
      '-------------------------------------')
      300 format(' ')

   end subroutine write_end2

end module ModWrite